#!/bin/zsh
# THEA BACKUP SCRIPTS
# 
# Mount the backup volume - to be launched via a GUI button
# Note: This script actuall runs thea-umount

source /usr/local/share/thea/config
source /usr/local/share/thea/functions

check_gui

echof_date=0
echof_silent=1
echof_color=1

maybe_disable_color

(
	echo "10"
	echo "# Unmounting backup volume"

	do_umount "gksudo"
	ret=$?
	if [ ${ret} -eq 0 ]
	then
		success=1
		echo "90"
		echo "# Backup volume ${BACKUP_VOLUME} has been unmounted"
		sleep ${INFO_DELAY}
	elif [ ${ret} -eq 2 ]
	then
		success=1
		echo "90"
		echo "# Backup volume ${BACKUP_VOLUME} is not mounted"
		sleep ${INFO_DELAY}
	else
		success=0
	fi

	echo "100"

	if [ ${success} -eq 0 ]
	then
		yad --error \
			--title="Error" \
			--text="Unable to unmount backup volume ${BACKUP_VOLUME}" 2>> /dev/null
	fi
) |
yad --progress \
	--width=480 \
	--title="Unmounting backup volume" \
	--text="Unmounting ${BACKUP_VOLUME}" \
	--percentage=0 \
	--pulsate \
	--auto-close \
	--no-buttons

exit 0
