#!/bin/zsh
# THEA BACKUP SCRIPTS
# 
# Run thea-backup-interactive inside a terminal - to be launched via a GUI button

source /usr/local/share/thea/config
source /usr/local/share/thea/functions

check_gui

echof_date=0
echof_silent=1

${TERMINAL_CMD} ${TERMINAL_CMD_ARGS} -e "thea-backup-interactive ${@} andwait"

exit 0
